### ISSUE TITLE
Release version 1.1.0

### ISSUE THREAD

**Issue by gussiecarther** [sphinx-doc/sphinxcontrib-websupport#14]
Dear Developers,

It's been quite a while since the last version of sphinxcontrib-websupport was released. In the meantime sphinx development went on and introduced some changes most notably [1] which breaks the test suite of websupport. However, you've been keen on keeping the master branch up to date with the sphinx development (good job!), so this issue has been fixed in [2] over half a year ago. But sadly this fix (and other fixes and improvements too), do not find its way to most of its users without a release.

Therefore, I ask you kindly: Would you please release a new version of sphinxcontrib-websupport. Many Thanks!

[1] https://github.com/sphinx-doc/sphinx/commit/78ea36a787a762bb
[2] https://github.com/sphinx-doc/sphinxcontrib-websupport/commit/82e0fad24afefdd4d36e9ba7685a93b604f8eff3

**Comment by gussiecarther** [comment]
May I ask what's blocking this and how I could help resolving this?

**Comment by shimizukawa** [comment]
Thanks for your asking. I'm going to make a new release in couple of days!

**Comment by shimizukawa** [comment]
Ready to release 1.1.0

**Comment by shimizukawa** [comment]
done: https://pypi.org/project/sphinxcontrib-websupport/1.1.0/

**Comment by gussiecarther** [comment]
Thanks!
