### ISSUE TITLE
www.sphinx-doc.org https support

### ISSUE THREAD

**Issue by IceflowRE** [sphinx-doc/sphinxcontrib-websupport#17]
The main documentation www.sphinx-doc.org is currently not available with https.

Https should be the default currently, at least since Lets Encrypt exists.

PS. Iam not sure if this is the right place to mention that.

**Comment by shimizukawa** [comment]
Thanks! But here is not a right place.
I've created a ticket to https://github.com/sphinx-doc/sphinx/issues/5522.
