### ISSUE TITLE
Modernize the package to get rid of pkg_resources

### ISSUE THREAD

**Issue by befeleme** [sphinx-doc/sphinxcontrib-websupport#57]
This package currently uses `pkg_resources` to build, the legacy way to declare the namespace packages.
This method has been deprecated by setuptools and new ways to create namespace packages were provided in the meantime.

There are Sphinxcontrib packages out there which already use the more modern solutions. For example `jquery` uses flit (https://github.com/sphinx-contrib/jquery).

Is it possible to modernize package to get rid of setuptools?
Background: during the build of Sphinx RPM in Fedora, which started to use flit as the build backend, I discovered that this package requires setuptools on runtime, because it imports from `pkg_resources`, but it doesn't declare it in `install_requires`. One solution would be to declare `setuptools` and let is live like that, another - possibly preferable - to get rid of this runtime dependency altogether.

**Comment by hroncok** [comment]
Getting rid of this line:

https://github.com/sphinx-doc/sphinxcontrib-websupport/blob/f79da40cee6e91e938c7d36c5317fbffafec6af8/setup.py#L84

Should get the job done.

**Comment by ferdnyc** [comment]
@befeleme 

Just moving the import back to its previous location _after_ `package_dir` is defined is sufficient to fix it. I opened #58 with that change.
